2019-12-13 20:39:13,961 ERROR: Exception on /reset_password_request [GET] [in c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Gavin\Downloads\microblog\app\routes.py", line 129, in reset_password_request
    form = ResetPasswordRequestForm()
NameError: name 'ResetPasswordRequestForm' is not defined
2019-12-13 20:40:46,674 INFO: Microblog startup [in C:\Users\Gavin\Downloads\microblog\app\__init__.py:46]
2019-12-13 20:40:52,720 ERROR: Exception on /reset_password_request [GET] [in c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Gavin\Downloads\microblog\app\routes.py", line 129, in reset_password_request
    form = ResetPasswordRequestForm()
NameError: name 'ResetPasswordRequestForm' is not defined
2019-12-13 20:42:19,099 INFO: Microblog startup [in C:\Users\Gavin\Downloads\microblog\app\__init__.py:46]
2019-12-13 20:42:24,868 ERROR: Exception on /reset_password_request [POST] [in c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Gavin\Downloads\microblog\app\routes.py", line 133, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2019-12-13 20:45:09,801 ERROR: Exception on /reset_password_request [POST] [in c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\gavin\downloads\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Gavin\Downloads\microblog\app\routes.py", line 133, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2019-12-13 21:04:16,411 INFO: Microblog startup [in C:\Users\Gavin\Downloads\microblog\app\__init__.py:46]
